# From: https://github.com/shuhaoliu/docker-clion-dev/blob/master/docker-compose.yml

version: '3'

services:
  gdbserver:
    build:
      context: ./
      dockerfile: ./Dockerfile

    # Tag our container
    image: clion_dev

    # Secure computing mode (seccomp) is a Linux kernel feature. You can use it to restrict
    # the actions available within the container.
    #
    # The default seccomp profile provides a sane default for running containers
    # with seccomp and disables around 44 system calls out of 300+
    security_opt:
      - seccomp:unconfined

    # Specify custom container name. Because Docker container names must be unique, you
    # cannot scale a service beyond 1 container if you have specified a custom name.
    # Since this is a dev container only intended to be running independently, best to restrict this.
    container_name: debug

    # SSH to 7776 as to not interfere with any other SSH services running (ideally), 7777 for GDB debugging
    ports:
      - "7776:22"
      - "7777:7777"

    # Share our current directory with the container
    volumes:
      - .:/home/debugger/code

    # Set our default working directory
    working_dir: /home/debugger/code

    # Network host name
    hostname: debug
